env:
  es6: true
  node: false
  mocha: true
  browser: true
  jquery: true
#rules:
  # strict: [error, global]
#globals:
plugins: ['react']
extends: [ 'eslint:recommended', 'plugin:react/recommended' ]
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
globals:
  locale: true
  localesList: true