# Configuration file for the App Engine deployment

runtime: custom #custom means that we are using the Dockerfile
env: flex
health_check:
  enable_health_check: False
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.9
beta_settings:
  cloud_sql_instances: grottocenter-beta:europe-west1:grottocenter-demo-db
